### PR TITLE
duplicate cfp page into call for proposal

### LINKED ISSUE #48: Duplicate call-for-paper page into call-for-proposal
duplicate call-for-paper page into call-for-proposal
I'd like to have a component to handle that

### PR DESCRIPTION
**Pull request by ridhof**
resolve #48 
duplicate cfp page into call for proposal so that people who used to call-to-proposal slug can view the cfp content

### CODE REVIEW

**Comment by adifdwimaulana** [comment]
mas @ridhof ini kalo case seperti ini kayanya lebih baik di-handling di level middleware deh dengan router, instead of dibikinin pages sendiri. Jadi ketika user ketik call-for-proposal akan otomatis di-redirect ke call-for-paper

**Comment by ridhof** [comment]
hoo belum pernah eksplor, ku coba cari dulu yak

**Comment by ridhof** [comment]
udah ku fix yak mas, pake middleware route. baru tau bisa gini hahaha
mintol direview lagi yak @adifdwimaulana

**Review by adifdwimaulana — APPROVED** [review]
lgtm!

**Pull request merged**
